version: "1"  # Version must be a string
services:
  - type: web
    name: my-twilio-bot
    runtime: python   # Specify the runtime here
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: "your_actual_account_sid"
      - key: TWILIO_AUTH_TOKEN
        value: "your_actual_auth_token"
      - key: TWILIO_PHONE_NUMBER
        value: "your_actual_twilio_phone_number"